### ISSUE TITLE
Building阶段报错

### ISSUE THREAD

**Issue by Young-Lord** [azwhikaru/Action-Recovery-builder#3]
错误信息：
```
[ 99% 14742/14750] Target boot image: /home/runner/work/Action-Recovery-builder/Action-Recovery-builder/workspace/out/target/product/hi3635/boot.img
FAILED: /home/runner/work/Action-Recovery-builder/Action-Recovery-builder/workspace/out/target/product/hi3635/boot.img 
/bin/bash -c "(/home/runner/work/Action-Recovery-builder/Action-Recovery-builder/workspace/out/host/linux-x86/bin/mkbootimg  --kernel /home/runner/work/Action-Recovery-builder/Action-Recovery-builder/workspace/out/target/product/hi3635/kernel --ramdisk /home/runner/work/Action-Recovery-builder/Action-Recovery-builder/workspace/out/target/product/hi3635/ramdisk.img --base 0x00678000 --pagesize 2048 --cmdline \"mem=3072M mmcparts=mmcblk0:p1(vrl),p2(vrl_backup),p6(modemnvm_factory),p9(splash),p10(modemnvm_backup),p11(modemnvm_img),p12(modemnvm_system),p14(3rdmodemnvm),p15(3rdmodemnvmback),p17(modem_om),p20(modemnvm_update),p30(modem),p31(modem_dsp),p32(dfx),p33(3rdmodem) androidboot.selinux=enforcing buildvariant=eng\" --os_version 16.1.0 --os_patch_level 2099-12-31 --ramdisk_offset 0x07588000 --tags_offset 0xffb88000 --output /home/runner/work/Action-Recovery-builder/Action-Recovery-builder/workspace/out/target/product/hi3635/boot.img ) && (true )"
Traceback (most recent call last):
  File "/home/runner/work/Action-Recovery-builder/Action-Recovery-builder/workspace/out/host/linux-x86/bin/mkbootimg", line 216, in <module>
    main()
  File "/home/runner/work/Action-Recovery-builder/Action-Recovery-builder/workspace/out/host/linux-x86/bin/mkbootimg", line 207, in main
    img_id = write_header(args)
  File "/home/runner/work/Action-Recovery-builder/Action-Recovery-builder/workspace/out/host/linux-x86/bin/mkbootimg", line 77, in write_header
    (args.os_version << 11) | args.os_patch_level)) # os version and patch level
struct.error: 'I' format requires 0 <= number <= 4294967295
[ 99% 14743/14750] build /home/runner/work/Action-Recovery-builder/Action-Recovery-builder/workspace/out/target/product/hi3635/obj_arm/SHARED_LIBRARIES/libbmlutils_intermediates/teamwin
ninja: build stopped: subcommand failed.
06:28:03 ninja failed with: exit status 1
Error: Process completed with exit code 1.
```
代码位于<https://github.com/Young-Lord/Action-Recovery-builder> 和 <https://github.com/Young-Lord/android_device_unknown_hi3635>

设备是华为荣耀X2，设备树使用`twrpdtgen`提取

**Comment by Young-Lord** [comment]
[logs_1.zip](https://github.com/azwhikaru/Action-Recovery-builder/files/7574059/logs_1.zip)
详细log

**Comment by azwhikaru** [comment]
华为设备使用 twrpdtgen 貌似要加特殊的专用参数，此外这个工具不是万能的，并不能很好的支持麒麟
